# Generated by Django 4.2.4 on 2023-09-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_class_semester_remove_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
