# Generated by Django 4.2.4 on 2023-09-25 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_student_lecturer_alter_class_lecturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lecturer', to='attendance.lecturer'),
        ),
    ]
