# Generated by Django 4.2.4 on 2023-09-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_class_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='classInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
    ]
