# Generated by Django 4.2.4 on 2023-09-26 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_enrollment_classinfo_alter_enrollment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='classInfo',
        ),
        migrations.AddField(
            model_name='class',
            name='enrollments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.enrollment'),
        ),
        migrations.AlterField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Class', to='attendance.lecturer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='attendance.semester'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
    ]
