# Generated by Django 4.2.4 on 2023-10-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_class_course_alter_class_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='enrollments',
            field=models.ManyToManyField(blank=True, null=True, to='attendance.enrollment'),
        ),
    ]
