# Generated by Django 4.2.4 on 2023-10-06 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_alter_class_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('attended', 'Attended'), ('absent', 'Absent')], max_length=10)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.enrollment')),
            ],
        ),
    ]
