# Generated by Django 4.2.4 on 2023-10-06 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_collegeday_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
